language: python
build_image: drydock/u12pyt:prod
python:
  - 2.6
  - 2.7
  #- 3.2
  #- 3.3
  #- 3.4
  #- pypy

# Make folders for the reports
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  # exclude
#branches:
 #  - TEST


#cache: true
#integrations:
#  notifications:
#    - integrationName: hipchat
#      type: hipchat
#      recipients:
#        - "@VootlaChaitanya"
#        - "#roomOne"
#      on_success: always
#      on_failure: always
jobs:
  - name: pipelines-demo-manifest-mini
    type: manifest
    steps:
      - IN: pipelines-demo-image-mini
      - TASK: managed
    on_success:
      - NOTIFY: irc-mini
  - name: deploy-pipelines-demo-mini
    type: deploy
    flags:
      - job-flag-mini
    steps:
      - IN: pipelines-demo-manifest-mini
      - IN: ecs-cluster-mini
      - IN: docker-options-mini
      - IN: replicas-mini
      - TASK: managed
        deployMethod: upgrade
  - name: runSh-mini
    type: runSh
    runtime:
      nodePool: c7-test
    allowPublicAccess: true
    steps:
      - IN: pipelines-demo-manifest-mini
      - TASK:
          - script: echo 'This block executes when the TASK starts'
          - script: echo "versionName=satble" >> $JOB_STATE/runSh.env;
  - name: runSh3-mini
    type: runSh
    steps:
      - IN: deploy-pipelines-demo-mini
      - TASK:
          - script: echo 'This block executes when the TASK starts'
          - script: echo "versionName=satble" >> $JOB_STATE/runSh3.env;
  - name: runSh-test
    type: runSh
    steps:
      - IN: replicas-mini
      - TASK:
          - script: echo 'This block executes when the TASK starts'
          - script: echo "versionName=satble" >> $JOB_STATE/runSh3.env;
  - name: mini-downstream-parent
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: mini-downstream-ancestor
      - TASK:
          - script: echo 'This block executes when the TASK starts'
          - script: echo "versionName=satble" >> $JOB_STATE/runSh.env;
  - name: mini-downstream-ancestor
    type: runSh
    allowPublicAccess: true
    steps:
      - TASK:
          - script: echo 'This block executes when the TASK starts'
          - script: echo "versionName=satble" >> $JOB_STATE/runSh.env;
resources:
  - name: pipelines-demo-image-mini
    type: image
    integration: shipdeploy
    pointer:
      sourceName: >-
        shippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamples/samplepipelinesdemo
      isPull: false
    seed:
      versionName: latest
  - name: replicas-mini
    type: replicas
    version:
      count: 2
    flags:
      - replicas-mini
  - name: docker-options-mini
    type: dockerOptions
    version:
      portMappings:
        - '80:80'
  - name: ecs-cluster-mini
    type: cluster
    integration: aws
    pointer:
      sourceName: my-cluster
      region: us-west-2
  - name: irc-mini
    type: notification
    pointer:
      method: irc
      recipients:
        - 'chat.freenode.net#test-rc123'
  - name: pipelines-test-orphan-res
    type: image
    integration: shipdeploy
    pointer:
      sourceName: >-
        shippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamples/samplepipelinesdemo
      isPull: false
    seed:
      versionName: latestresources

  - name: version
    type: version
    versionTemplate:
      versionName: "a"
    
