language: python
build_image: drydock/u12pyt:prod
python:
  - 2.6
  - 2.7
  #- 3.2
  #- 3.3
  #- 3.4
  #- pypy

# Make folders for the reports
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  # exclude
#branches:
 #  - TEST


#cache: true
#integrations:
#  notifications:
#    - integrationName: hipchat
#      type: hipchat
#      recipients:
#        - "@VootlaChaitanya"
#        - "#roomOne"
#      on_success: always
#      on_failure: alwaysjobs:
jobs:
  - name: manifest-test
    type: manifest
    steps:
      - IN: file
        applyTo:
          - file
      - IN: trigger
      - TASK: managed
  - name: manifest-test-child
    type: manifest
    steps:
      - IN: manifest-test
        switch: 'off'
      - IN: version
        switch: 'off'
      - TASK: managed
resources:
  - name: file
    type: file
    integration: shipdeploy
    versionTemplate:
      versionName: vn
      sourceName: sn
  - name: version
    type: version
    versionTemplate:
      versionName: 0.0.1
  - name: trigger
    type: trigger
    versionTemplate:
      counter: '1'
  - name: time
    type: time
    versionTemplate:
      interval: '1'
